### ISSUE TITLE
javax.persistence.OptimisticLockException when uploading document with images

### ISSUE THREAD

**Issue by tcpkump** [justmiles/go-markdown2confluence#64]
I'm encountering an interesting issue that I can only consistently reproduce in Bitbucket Pipelines. Any time I add or change an image link, the `markdown2confluence` push of that document will fail on the first try like so

```
time="2023-02-28T16:33:31Z" level=debug msg="POST <redacted>/child/attachment"
time="2023-02-28T16:33:32Z" level=debug msg="Response Status Code: 500"
time="2023-02-28T16:33:32Z" level=debug msg="Response Body: '{\"statusCode\":500,\"message\":\"javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.atlassian.confluence.pages.Attachment#4362829904]\"}'"
time="2023-02-28T16:33:32Z" level=error msg="javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.atlassian.confluence.pages.Attachment#4362829904]"
[javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.atlassian.confluence.pages.Attachment#4362829904]]
GCP pgbouncer Deployment: <redacted>
Unable to upload markdown file Home/GCP pgbouncer [Deployment.md](http://deployment.md/): 
	javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.atlassian.confluence.pages.Attachment#4362829904]
```

However, the `markdown2confluence` import will work successfully if I retry the pipeline, so it seems to be related to quick subsequent modifications to the page. Also, if I simply try to push this up from my local workstation, I get no such issues, which is also interesting.

I don't really suspect it's an issue with this application, but maybe there's a way to handle this and retry?

**Comment by lebergarrett** [comment]
I apologize in advance if this isn't enough for you to recreate the issue. I intend to revisit this and put more together if this isn't sufficient. Though it may be a couple weeks. If it comes down to that I'll see if I can learn enough to put together my first PR :)

I'm building a custom Dockerfile for use in the Bitbucket pipeline so I can use the bash shell in the container for steps within the pipeline. Dockerfile: 

```Dockerfile
FROM debian

RUN apt-get -y update && apt-get -y install curl
RUN curl -LO https://github.com/justmiles/go-markdown2confluence/releases/download/v3.4.2/go-markdown2confluence_3.4.2_linux_x86_64.tar.gz
RUN tar -xzvf go-markdown2confluence_3.4.2_linux_x86_64.tar.gz -C /usr/local/bin/ markdown2confluence
```

And here is my bitbucket-pipelines.yml

```yaml
pipelines:
  branches:
    main:
      - step:
          name: Push to Confluence
          image: 
            name: us-central1-docker.pkg.dev/<redacted>/<redacted>/markdown2confluence
            username: _json_key
            password: '$GOOGLE_ARTIFACT_REGISTRY_SERVICE_ACCOUNT_KEY'
          script:
            - markdown2confluence --debug --space $CONFLUENCE_SPACE Home

```

In the markdown file, I simply have a relative link to an image with is stored in the same repo.
